# 服务器配置
server:
  ip: 127.0.0.1
  port: 9080
  servlet:
    context-path: /

# Knife4j配置
knife4j:
  basic:
    # 自定义Swagger-ui的访问路径
    view-url: /V3/

# Spring配置
spring:
  application:
    name: cms
  ssdb:
    host: ip
    port: 6379
    max-active: 5
    timeout: 10000
    password: password
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/cms?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      max-active: 20
      min-idle: 3
      max-wait: 60000
      max-open-prepared-statements: 20
      validation-query: SELECT 1
      validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      poolPreparedStatements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: 123456789
        allow: 127.0.0.1

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  mybatis:
    logImpl: log4j2

# JWT配置
jwt:
  secret: secret
  expiration: 604800

# MyBatis Plus配置
mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_null

# 日志配置
logging:
  level:
    root: info
    com.trojan.cms: debug
  config: classpath:logback-spring.xml
  file:
    path: ./logs

# 阿里云配置
ali:
  sms:
    accessKeyId: key
    accessSecret: secret
    signName: name
    templateCode: code
  oss:
    accessKeyId: key
    accessKeySecret: secret
    endpoint: endpoint
    bucketName: name
    bucketUrl: url
